# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R8Kr9c_G6qedZFwp8UlN5Hr-KFdYAt2W

# Data Science Tools and Ecosystem 
`In this notebook, Data Science Tools and Ecosystem are summarized.`

Some of the popular languages that Data Scientists use are:



1.   R studio
2.   Python

3.  Julia

Some of the commonly used libraries used by Data Scientists include:

1.   SKLEARN
2.   PANDAS
3.   NUMPY

Data Science Tools


1.   Apache Hadoop
2.   Informatica PowerCenter


3.   Microsoft HD Insights

### Below are a few examples of evaluating arithmetic expressions in Python
"""

x=(3*4)+5
print(x)

#This a simple arithmetic expression to mutiply then add integers

min=200
hour= min/24
print(hour)

# This will convert 200 minutes to hours by diving by 60

"""#Objectives:


*   R studio
 
*   Python

*   Julia

##Author

Bhavnish Singhall
"""

